---
- name: Pull docker image of frontend
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: vtandonv/communityhubfrontend
        source: pull
     
     - name: Create front-end container
       docker_container:
        name: angular-con1
        image: vtandonv/communityhubfrontend
        ports:
          - "4200:4200"
 
 
